spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ty_yak_be}
    username: ${DATASOURCE_USERNAME:ty_yak_be}
    password: ${DATASOURCE_PASSWORD:very_very_secure_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/db.changelog-master.yml
    user: ${DATASOURCE_USERNAME:ty_yak_be}
    password: ${DATASOURCE_PASSWORD:very_very_secure_password}
    default-schema: public
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/ty_yak_be}
  sendgrid:
    api-key: ${SENDGRID_API_KEY:key}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    path: /docs

jwt:
  secret: ${JWT_SECRET:very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_very_strong_secret}

s3:
  access-key: ${AWS_ACCESS_KEY:test}
  secret-key: ${AWS_SECRET_KEY:test}
  service-endpoint: s3.eu-central-1.amazonaws.com
  signing-region: eu-central-1
  bucket-name: ${BUCKET_NAME:staging}
  folders:
    avatars: avatars

sendgrid:
  sender: ty.yak.main@gmail.com

token:
  expiration:
    time:
      ms: 600000000
  refresh:
    expiration:
      time:
        ms: 2592000000000