package com.ty_yak.auth.model.enums;

public enum BusinessLogicException {

    INCORRECT_EMAIL_OR_PASSWORD,
    INCORRECT_EMAIL_OR_USERNAME,
    INCORRECT_CONFIRM_CODE,
    CODE_EXPIRED,
    USERNAME_ALREADY_EXISTS,
    EMAIL_ALREADY_EXISTS,
    INVITATION_DECLINED,
    NOT_VALID_PASSWORD,
    WRONG_AUTHORIZATION_TYPE,
    WRONG_AUTHORIZATION_TYPE_FOR_PASSWORD_RECOVERING,
    EMAIL_FOR_PASSWORD_RECOVER_NOT_FOUND
}
